// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Element struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content        *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Name           *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Styles         string                 `protobuf:"bytes,5,opt,name=styles,proto3" json:"styles,omitempty"` // JSON string
	TailwindStyles *string                `protobuf:"bytes,6,opt,name=tailwind_styles,json=tailwindStyles,proto3,oneof" json:"tailwind_styles,omitempty"`
	Src            *string                `protobuf:"bytes,7,opt,name=src,proto3,oneof" json:"src,omitempty"`
	Href           *string                `protobuf:"bytes,8,opt,name=href,proto3,oneof" json:"href,omitempty"`
	ParentId       *string                `protobuf:"bytes,9,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	PageId         *string                `protobuf:"bytes,10,opt,name=page_id,json=pageId,proto3,oneof" json:"page_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,11,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Order          int32                  `protobuf:"varint,12,opt,name=order,proto3" json:"order,omitempty"`
	Settings       *string                `protobuf:"bytes,13,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	Elements       []*Element             `protobuf:"bytes,14,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Element) Reset() {
	*x = Element{}
	mi := &file_proto_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Element) ProtoMessage() {}

func (x *Element) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Element.ProtoReflect.Descriptor instead.
func (*Element) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{0}
}

func (x *Element) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Element) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Element) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *Element) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Element) GetStyles() string {
	if x != nil {
		return x.Styles
	}
	return ""
}

func (x *Element) GetTailwindStyles() string {
	if x != nil && x.TailwindStyles != nil {
		return *x.TailwindStyles
	}
	return ""
}

func (x *Element) GetSrc() string {
	if x != nil && x.Src != nil {
		return *x.Src
	}
	return ""
}

func (x *Element) GetHref() string {
	if x != nil && x.Href != nil {
		return *x.Href
	}
	return ""
}

func (x *Element) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *Element) GetPageId() string {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return ""
}

func (x *Element) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Element) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Element) GetSettings() string {
	if x != nil && x.Settings != nil {
		return *x.Settings
	}
	return ""
}

func (x *Element) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

type SaveSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Elements      string                 `protobuf:"bytes,4,opt,name=elements,proto3" json:"elements,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProjectId     string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotRequest) Reset() {
	*x = SaveSnapshotRequest{}
	mi := &file_proto_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotRequest) ProtoMessage() {}

func (x *SaveSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotRequest.ProtoReflect.Descriptor instead.
func (*SaveSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveSnapshotRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SaveSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveSnapshotRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SaveSnapshotRequest) GetElements() string {
	if x != nil {
		return x.Elements
	}
	return ""
}

func (x *SaveSnapshotRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SaveSnapshotRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type SaveSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSnapshotResponse) Reset() {
	*x = SaveSnapshotResponse{}
	mi := &file_proto_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSnapshotResponse) ProtoMessage() {}

func (x *SaveSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSnapshotResponse.ProtoReflect.Descriptor instead.
func (*SaveSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{2}
}

func (x *SaveSnapshotResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProjectElementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectElementsRequest) Reset() {
	*x = ProjectElementsRequest{}
	mi := &file_proto_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectElementsRequest) ProtoMessage() {}

func (x *ProjectElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectElementsRequest.ProtoReflect.Descriptor instead.
func (*ProjectElementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectElementsRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ProjectElementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Element             `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectElementsResponse) Reset() {
	*x = ProjectElementsResponse{}
	mi := &file_proto_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectElementsResponse) ProtoMessage() {}

func (x *ProjectElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectElementsResponse.ProtoReflect.Descriptor instead.
func (*ProjectElementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_service_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectElementsResponse) GetElements() []*Element {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_proto_service_proto protoreflect.FileDescriptor

const file_proto_service_proto_rawDesc = "" +
	"\n" +
	"\x13proto/service.proto\x12\x05proto\"\xfe\x03\n" +
	"\aElement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x00R\acontent\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06styles\x18\x05 \x01(\tR\x06styles\x12,\n" +
	"\x0ftailwind_styles\x18\x06 \x01(\tH\x02R\x0etailwindStyles\x88\x01\x01\x12\x15\n" +
	"\x03src\x18\a \x01(\tH\x03R\x03src\x88\x01\x01\x12\x17\n" +
	"\x04href\x18\b \x01(\tH\x04R\x04href\x88\x01\x01\x12 \n" +
	"\tparent_id\x18\t \x01(\tH\x05R\bparentId\x88\x01\x01\x12\x1c\n" +
	"\apage_id\x18\n" +
	" \x01(\tH\x06R\x06pageId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"project_id\x18\v \x01(\tR\tprojectId\x12\x14\n" +
	"\x05order\x18\f \x01(\x05R\x05order\x12\x1f\n" +
	"\bsettings\x18\r \x01(\tH\aR\bsettings\x88\x01\x01\x12*\n" +
	"\belements\x18\x0e \x03(\v2\x0e.proto.ElementR\belementsB\n" +
	"\n" +
	"\b_contentB\a\n" +
	"\x05_nameB\x12\n" +
	"\x10_tailwind_stylesB\x06\n" +
	"\x04_srcB\a\n" +
	"\x05_hrefB\f\n" +
	"\n" +
	"_parent_idB\n" +
	"\n" +
	"\b_page_idB\v\n" +
	"\t_settings\"\xa6\x01\n" +
	"\x13SaveSnapshotRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\belements\x18\x04 \x01(\tR\belements\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\"0\n" +
	"\x14SaveSnapshotResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x16ProjectElementsRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\"E\n" +
	"\x17ProjectElementsResponse\x12*\n" +
	"\belements\x18\x01 \x03(\v2\x0e.proto.ElementR\belements2\xae\x01\n" +
	"\x0eElementService\x12G\n" +
	"\fSaveSnapshot\x12\x1a.proto.SaveSnapshotRequest\x1a\x1b.proto.SaveSnapshotResponse\x12S\n" +
	"\x12GetProjectElements\x12\x1d.proto.ProjectElementsRequest\x1a\x1e.proto.ProjectElementsResponseB\x11Z\x0fmy-go-app/protob\x06proto3"

var (
	file_proto_service_proto_rawDescOnce sync.Once
	file_proto_service_proto_rawDescData []byte
)

func file_proto_service_proto_rawDescGZIP() []byte {
	file_proto_service_proto_rawDescOnce.Do(func() {
		file_proto_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)))
	})
	return file_proto_service_proto_rawDescData
}

var file_proto_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_service_proto_goTypes = []any{
	(*Element)(nil),                 // 0: proto.Element
	(*SaveSnapshotRequest)(nil),     // 1: proto.SaveSnapshotRequest
	(*SaveSnapshotResponse)(nil),    // 2: proto.SaveSnapshotResponse
	(*ProjectElementsRequest)(nil),  // 3: proto.ProjectElementsRequest
	(*ProjectElementsResponse)(nil), // 4: proto.ProjectElementsResponse
}
var file_proto_service_proto_depIdxs = []int32{
	0, // 0: proto.Element.elements:type_name -> proto.Element
	0, // 1: proto.ProjectElementsResponse.elements:type_name -> proto.Element
	1, // 2: proto.ElementService.SaveSnapshot:input_type -> proto.SaveSnapshotRequest
	3, // 3: proto.ElementService.GetProjectElements:input_type -> proto.ProjectElementsRequest
	2, // 4: proto.ElementService.SaveSnapshot:output_type -> proto.SaveSnapshotResponse
	4, // 5: proto.ElementService.GetProjectElements:output_type -> proto.ProjectElementsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_service_proto_init() }
func file_proto_service_proto_init() {
	if File_proto_service_proto != nil {
		return
	}
	file_proto_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_service_proto_rawDesc), len(file_proto_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_service_proto_goTypes,
		DependencyIndexes: file_proto_service_proto_depIdxs,
		MessageInfos:      file_proto_service_proto_msgTypes,
	}.Build()
	File_proto_service_proto = out.File
	file_proto_service_proto_goTypes = nil
	file_proto_service_proto_depIdxs = nil
}
