// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ElementService_SaveSnapshot_FullMethodName       = "/proto.ElementService/SaveSnapshot"
	ElementService_GetProjectElements_FullMethodName = "/proto.ElementService/GetProjectElements"
)

// ElementServiceClient is the client API for ElementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElementServiceClient interface {
	SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error)
	GetProjectElements(ctx context.Context, in *ProjectElementsRequest, opts ...grpc.CallOption) (*ProjectElementsResponse, error)
}

type elementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewElementServiceClient(cc grpc.ClientConnInterface) ElementServiceClient {
	return &elementServiceClient{cc}
}

func (c *elementServiceClient) SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSnapshotResponse)
	err := c.cc.Invoke(ctx, ElementService_SaveSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elementServiceClient) GetProjectElements(ctx context.Context, in *ProjectElementsRequest, opts ...grpc.CallOption) (*ProjectElementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectElementsResponse)
	err := c.cc.Invoke(ctx, ElementService_GetProjectElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElementServiceServer is the server API for ElementService service.
// All implementations must embed UnimplementedElementServiceServer
// for forward compatibility.
type ElementServiceServer interface {
	SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error)
	GetProjectElements(context.Context, *ProjectElementsRequest) (*ProjectElementsResponse, error)
	mustEmbedUnimplementedElementServiceServer()
}

// UnimplementedElementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElementServiceServer struct{}

func (UnimplementedElementServiceServer) SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSnapshot not implemented")
}
func (UnimplementedElementServiceServer) GetProjectElements(context.Context, *ProjectElementsRequest) (*ProjectElementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectElements not implemented")
}
func (UnimplementedElementServiceServer) mustEmbedUnimplementedElementServiceServer() {}
func (UnimplementedElementServiceServer) testEmbeddedByValue()                        {}

// UnsafeElementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElementServiceServer will
// result in compilation errors.
type UnsafeElementServiceServer interface {
	mustEmbedUnimplementedElementServiceServer()
}

func RegisterElementServiceServer(s grpc.ServiceRegistrar, srv ElementServiceServer) {
	// If the following call pancis, it indicates UnimplementedElementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ElementService_ServiceDesc, srv)
}

func _ElementService_SaveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElementServiceServer).SaveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElementService_SaveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElementServiceServer).SaveSnapshot(ctx, req.(*SaveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ElementService_GetProjectElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectElementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElementServiceServer).GetProjectElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElementService_GetProjectElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElementServiceServer).GetProjectElements(ctx, req.(*ProjectElementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ElementService_ServiceDesc is the grpc.ServiceDesc for ElementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ElementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ElementService",
	HandlerType: (*ElementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveSnapshot",
			Handler:    _ElementService_SaveSnapshot_Handler,
		},
		{
			MethodName: "GetProjectElements",
			Handler:    _ElementService_GetProjectElements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
