package routes

import (
	"my-go-app/internal/handlers"
	"my-go-app/internal/repositories"
	"my-go-app/internal/services"
	"my-go-app/pkg/middleware"

	"github.com/gofiber/fiber/v2"
)

func PrivateRoutes(app *fiber.App, repos *repositories.RepositoriesInterface, cloudinaryService *services.CloudinaryService, invitationService *services.InvitationService) {
	elementService := services.NewElementWrapperService(repos.ElementRepository)
	projectService := services.NewProjectService(repos.ProjectRepository, repos.CollaboratorRepository, repos.UserRepository)
	pageService := services.NewPageService(repos.PageRepository, repos.ProjectRepository)
	snapshotService := services.NewSnapshotService(repos.SnapshotRepository, repos.ElementRepository, repos.ProjectRepository)
	contentTypeService := services.NewContentTypeService(repos.ContentTypeRepository)
	contentFieldService := services.NewContentFieldService(repos.ContentFieldRepository)
	contentItemService := services.NewContentItemService(repos.ContentItemRepository)
	imageService := services.NewImageService(repos.ImageRepository, cloudinaryService)
	marketplaceService := services.NewMarketplaceService(repos.MarketplaceRepository)
	customElementService := services.NewCustomElementService(repos.CustomElementRepository)
	customElementTypeService := services.NewCustomElementTypeService(repos.CustomElementTypeRepository)
	collaboratorService := services.NewCollaboratorService(repos.CollaboratorRepository, repos.ProjectRepository)
	commentService := services.NewCommentService(repos.CommentRepository, repos.MarketplaceRepository)
	elementCommentService := services.NewElementCommentService(repos.ElementCommentRepository, repos.ElementRepository, repos.ProjectRepository)
	userService := services.NewUserService(repos.UserRepository)
	eventWorkflowService := services.NewEventWorkflowService(repos.EventWorkflowRepository, repos.ProjectRepository)
	elementEventWorkflowService := services.NewElementEventWorkflowService(repos.ElementEventWorkflowRepository, repos.ElementRepository, repos.ProjectRepository, repos.PageRepository)

	elementHandler := handlers.NewElementHandler(elementService)
	projectHandler := handlers.NewProjectHandler(projectService)
	pageHandler := handlers.NewPageHandler(pageService)
	snapshotHandler := handlers.NewSnapshotHandler(snapshotService, repos.ElementRepository)
	contentTypeHandler := handlers.NewContentTypeHandler(contentTypeService)
	contentFieldHandler := handlers.NewContentFieldHandler(contentFieldService)
	contentItemHandler := handlers.NewContentItemHandler(contentItemService)
	imageHandler := handlers.NewImageHandler(imageService, cloudinaryService)
	marketplaceHandler := handlers.NewMarketplaceHandler(marketplaceService)
	customElementHandler := handlers.NewCustomElementHandler(customElementService)
	customElementTypeHandler := handlers.NewCustomElementTypeHandler(customElementTypeService)
	invitationHandler := handlers.NewInvitationHandler(invitationService)
	collaboratorHandler := handlers.NewCollaboratorHandler(collaboratorService)
	commentHandler := handlers.NewCommentHandler(commentService)
	elementCommentHandler := handlers.NewElementCommentHandler(elementCommentService)
	userHandler := handlers.NewUserHandler(userService)
	eventWorkflowHandler := handlers.NewEventWorkflowHandler(eventWorkflowService, elementEventWorkflowService)
	elementEventWorkflowHandler := handlers.NewElementEventWorkflowHandler(elementEventWorkflowService, projectService, pageService)

	group := app.Group("/api/v1", middleware.AuthenticateMiddleware)

	group.Get("/elements/:projectid", elementHandler.GetElements)
	group.Get("/elements/by-pages", elementHandler.GetElementsByPageIds)

	group.Get("/projects/user", projectHandler.GetProjectsByUser)
	group.Get("/projects/:projectid", projectHandler.GetProjectByID)
	group.Get("/projects/:projectid/pages", projectHandler.GetProjectPages)
	group.Delete("/projects/:projectid", projectHandler.DeleteProject)
	group.Patch("/projects/:projectid", projectHandler.UpdateProject)
	group.Delete("/projects/:projectid/pages/:pageid", pageHandler.DeletePage)

	group.Get("/pages/:projectid", pageHandler.GetPagesByProjectID)
	group.Get("/pages/:projectid/:pageid", pageHandler.GetPageByID)
	group.Post("/pages/:projectid", pageHandler.CreatePage)
	group.Patch("/pages/:projectid/:pageid", pageHandler.UpdatePage)

	group.Post("/snapshots/:projectid/save", snapshotHandler.SaveSnapshot)
	group.Get("/snapshots/:projectid", snapshotHandler.GetSnapshots)
	group.Get("/snapshots/:snapshotid", snapshotHandler.GetSnapshotByID)
	group.Delete("/snapshots/:snapshotid", snapshotHandler.DeleteSnapshot)

	group.Post("/content-types", contentTypeHandler.CreateContentType)
	group.Get("/content-types", contentTypeHandler.GetContentTypes)
	group.Get("/content-types/:id", contentTypeHandler.GetContentTypeByID)
	group.Patch("/content-types/:id", contentTypeHandler.UpdateContentType)
	group.Delete("/content-types/:id", contentTypeHandler.DeleteContentType)

	group.Post("/content-fields", contentFieldHandler.CreateContentField)
	group.Get("/content-fields/:contentTypeId", contentFieldHandler.GetContentFieldsByContentType)
	group.Get("/content-fields/by-id/:id", contentFieldHandler.GetContentFieldByID)
	group.Patch("/content-fields/:id", contentFieldHandler.UpdateContentField)
	group.Delete("/content-fields/:id", contentFieldHandler.DeleteContentField)

	group.Post("/content-items", contentItemHandler.CreateContentItem)
	group.Get("/content-items/:contentTypeId", contentItemHandler.GetContentItemsByContentType)
	group.Get("/content-items/by-id/:id", contentItemHandler.GetContentItemByID)
	group.Patch("/content-items/:id", contentItemHandler.UpdateContentItem)
	group.Delete("/content-items/:id", contentItemHandler.DeleteContentItem)

	group.Post("/images", imageHandler.UploadImage)
	group.Get("/images", imageHandler.GetUserImages)
	group.Get("/images/:imageid", imageHandler.GetImageByID)
	group.Delete("/images/:imageid", imageHandler.DeleteImage)

	group.Post("/marketplace", marketplaceHandler.CreateMarketplaceItem)
	group.Get("/marketplace", marketplaceHandler.GetMarketplaceItems)
	group.Get("/marketplace/:id", marketplaceHandler.GetMarketplaceItemByID)
	group.Patch("/marketplace/:id", marketplaceHandler.UpdateMarketplaceItem)
	group.Delete("/marketplace/:id", marketplaceHandler.DeleteMarketplaceItem)

	group.Post("/custom-elements", customElementHandler.CreateCustomElement)
	group.Get("/custom-elements", customElementHandler.GetCustomElements)
	group.Get("/custom-elements/:id", customElementHandler.GetCustomElementByID)
	group.Patch("/custom-elements/:id", customElementHandler.UpdateCustomElement)
	group.Delete("/custom-elements/:id", customElementHandler.DeleteCustomElement)

	group.Post("/custom-element-types", customElementTypeHandler.CreateCustomElementType)
	group.Get("/custom-element-types", customElementTypeHandler.GetCustomElementTypes)
	group.Get("/custom-element-types/:id", customElementTypeHandler.GetCustomElementTypeByID)
	group.Patch("/custom-element-types/:id", customElementTypeHandler.UpdateCustomElementType)
	group.Delete("/custom-element-types/:id", customElementTypeHandler.DeleteCustomElementType)

	group.Post("/invitations", invitationHandler.CreateInvitation)
	group.Post("/invitations/accept", invitationHandler.AcceptInvitation)
	group.Post("/invitations/:token/accept", invitationHandler.AcceptInvitation)
	group.Get("/invitations", invitationHandler.GetInvitationsByProject)
	group.Get("/invitations/project/:projectid", invitationHandler.GetInvitationsByProject)
	group.Get("/invitations/project/:projectid/pending", invitationHandler.GetPendingInvitationsByProject)
	group.Patch("/invitations/:invitationid/cancel", invitationHandler.CancelInvitation)
	group.Patch("/invitations/:invitationid/status", invitationHandler.UpdateInvitationStatus)
	group.Delete("/invitations/:id", invitationHandler.DeleteInvitation)
	group.Delete("/invitations/:invitationid", invitationHandler.DeleteInvitation)

	group.Post("/collaborators", collaboratorHandler.CreateCollaborator)
	group.Get("/collaborators/:projectid", collaboratorHandler.GetCollaboratorsByProject)
	group.Get("/collaborators/project/:projectid", collaboratorHandler.GetCollaboratorsByProject)
	group.Get("/collaborators/:collaboratorid", collaboratorHandler.GetCollaboratorByID)
	group.Patch("/collaborators/:id", collaboratorHandler.UpdateCollaboratorRole)
	group.Patch("/collaborators/:collaboratorid/role", collaboratorHandler.UpdateCollaboratorRole)
	group.Delete("/collaborators/:id", collaboratorHandler.DeleteCollaborator)
	group.Delete("/collaborators/:collaboratorid", collaboratorHandler.DeleteCollaborator)

	group.Post("/comments", commentHandler.CreateComment)
	group.Get("/comments/:id", commentHandler.GetCommentByID)
	group.Get("/comments", commentHandler.GetComments)
	group.Patch("/comments/:id", commentHandler.UpdateComment)
	group.Delete("/comments/:id", commentHandler.DeleteComment)

	group.Post("/element-comments", elementCommentHandler.CreateElementComment)
	group.Get("/element-comments/:id", elementCommentHandler.GetElementCommentByID)
	group.Get("/element-comments", elementCommentHandler.GetElementComments)
	group.Get("/elements/:elementId/comments", elementCommentHandler.GetElementComments)
	group.Get("/element-comments/author/:authorId", elementCommentHandler.GetCommentsByAuthorID)
	group.Get("/projects/:projectId/comments", elementCommentHandler.GetCommentsByProjectID)
	group.Patch("/element-comments/:id", elementCommentHandler.UpdateElementComment)
	group.Patch("/element-comments/:id/toggle-resolved", elementCommentHandler.ToggleResolvedStatus)
	group.Delete("/element-comments/:id", elementCommentHandler.DeleteElementComment)

	group.Get("/users/:userid", userHandler.SearchUsers)
	group.Get("/users/email/:email", userHandler.GetUserByEmail)
	group.Get("/users/username/:username", userHandler.GetUserByUsername)
	group.Get("/users/search", userHandler.SearchUsers)

	group.Post("/event-workflows", eventWorkflowHandler.CreateEventWorkflow)
	group.Get("/event-workflows/:projectid", eventWorkflowHandler.GetEventWorkflowsByProject)
	group.Get("/event-workflows/:id", eventWorkflowHandler.GetEventWorkflowByID)
	group.Patch("/event-workflows/:id", eventWorkflowHandler.UpdateEventWorkflow)
	group.Patch("/event-workflows/:id/enabled", eventWorkflowHandler.UpdateEventWorkflowEnabled)
	group.Delete("/event-workflows/:id", eventWorkflowHandler.DeleteEventWorkflow)
	group.Get("/event-workflows/:id/elements", eventWorkflowHandler.GetEventWorkflowElements)

	group.Post("/element-event-workflows", elementEventWorkflowHandler.CreateElementEventWorkflow)
	group.Get("/element-event-workflows/:id", elementEventWorkflowHandler.GetElementEventWorkflowByID)
	group.Get("/element-event-workflows", elementEventWorkflowHandler.GetElementEventWorkflows)
	group.Patch("/element-event-workflows/:id", elementEventWorkflowHandler.UpdateElementEventWorkflow)
	group.Delete("/element-event-workflows/:id", elementEventWorkflowHandler.DeleteElementEventWorkflow)
	group.Delete("/element-event-workflows/element/:elementId", elementEventWorkflowHandler.DeleteElementEventWorkflowsByElement)
	group.Delete("/element-event-workflows/workflow/:workflowId", elementEventWorkflowHandler.DeleteElementEventWorkflowsByWorkflow)
}