// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: proto/service.proto

package element

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ElementSerivice_SaveSnapshot_FullMethodName = "/element.ElementSerivice/SaveSnapshot"
)

// ElementSeriviceClient is the client API for ElementSerivice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ElementSeriviceClient interface {
	SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error)
}

type elementSeriviceClient struct {
	cc grpc.ClientConnInterface
}

func NewElementSeriviceClient(cc grpc.ClientConnInterface) ElementSeriviceClient {
	return &elementSeriviceClient{cc}
}

func (c *elementSeriviceClient) SaveSnapshot(ctx context.Context, in *SaveSnapshotRequest, opts ...grpc.CallOption) (*SaveSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSnapshotResponse)
	err := c.cc.Invoke(ctx, ElementSerivice_SaveSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ElementSeriviceServer is the server API for ElementSerivice service.
// All implementations must embed UnimplementedElementSeriviceServer
// for forward compatibility.
type ElementSeriviceServer interface {
	SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error)
	mustEmbedUnimplementedElementSeriviceServer()
}

// UnimplementedElementSeriviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedElementSeriviceServer struct{}

func (UnimplementedElementSeriviceServer) SaveSnapshot(context.Context, *SaveSnapshotRequest) (*SaveSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveSnapshot not implemented")
}
func (UnimplementedElementSeriviceServer) mustEmbedUnimplementedElementSeriviceServer() {}
func (UnimplementedElementSeriviceServer) testEmbeddedByValue()                         {}

// UnsafeElementSeriviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ElementSeriviceServer will
// result in compilation errors.
type UnsafeElementSeriviceServer interface {
	mustEmbedUnimplementedElementSeriviceServer()
}

func RegisterElementSeriviceServer(s grpc.ServiceRegistrar, srv ElementSeriviceServer) {
	// If the following call pancis, it indicates UnimplementedElementSeriviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ElementSerivice_ServiceDesc, srv)
}

func _ElementSerivice_SaveSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElementSeriviceServer).SaveSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ElementSerivice_SaveSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElementSeriviceServer).SaveSnapshot(ctx, req.(*SaveSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ElementSerivice_ServiceDesc is the grpc.ServiceDesc for ElementSerivice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ElementSerivice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "element.ElementSerivice",
	HandlerType: (*ElementSeriviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveSnapshot",
			Handler:    _ElementSerivice_SaveSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
